permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Syzygy Kendamas"
  description: |
    A small local kendama organization specializing in locally sources wooden kendamas, planting a tree for every sale over $30. Trees are in danger and we need to save them all!
  font_url: "https://use.typekit.net/cga8stj.css"
  colors:
    background: "--color-light"
    accent: "--color-primary"
    patterns:
      brand.logos: "--color-neutral-beige"
  rationales:
    typefaces.primary: |
      Brandon-grotesque was selected because it conveys a professional tone.
    typefaces.secondary: |
      Bodoni-urw was chosen because it compliments the serif typeface and its width is comparable.
    colors.primary: |
      The primary colour reprsents the earth. It should be used for all body copy and text against the white html background.
    colors.secondary: |
      The primary colours represent nature, trees and plants. The should be used for text in foregrounds.
