permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Syzygy Kendamas"
  description: |
  "A small local kendama organization specializing in locally sources wooden kendamas, planting a tree for every sale over $30. Trees are in danger and we need to save them all!"
  font_url: "https://use.typekit.net/cga8stj.css"
