title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      Default to using the basic cutton. It should always be used in front of light backgrounds.

  ghost:
    title: "Ghost"
    description: |
      The ghost button is specifically for banners, where it will be placed in front light background because the background is transparent.

  round:
    title: "Round"
    description: |
      The round button should be used to add a graphical element to the page.

  call-to-action:
    title: "Call-to-Action"
    description: |
      The Call-to-Action button is specifically used for banners with images. Use this button against a dark background as it has a more contrasting border colour.
    background: "--color-dark"

  light:
    title: "Light"
    description: |
      The light button should be used as a variation of the ghost button.
    background: "--color-secondary-whatever"

  cart:
    title: "Cart"
    description: |
      The cart button is used specifically to add items to the shopping cart.
