title: "Cards"
description: |
  Cards should be used to display products and images. Cards should be used within a grid system.

patterns:
  kendama:
    title: "Basic Light"
    description: |
      The basic card with a green border. Use against a light background.

  product2:
    title: "Basic Dark"
    description: |
      The basic card with a green border. Use against a dark background.

  carosel:
    title: "Carosel Javascript"
    description: |
      The carosel button should be used to scroll through images while remaining on the same page. Should be hidden on small sizes and only appear on medium and above.

  prodinfo:
    title: "Product Info"
    description: |
      The product info card should be used to show the option to view different perspectives of the items. This should also be used as a child of the product card.

  product-card:
    width: 400
    description: |
      The product card is used on the product listing page to display each availavble product.
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
